// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAoQWA-CUDivQp9tsLRC21VBp_A8Q539g0',
    appId: '1:390668051355:android:c849b42614a226b7d6f73e',
    messagingSenderId: '390668051355',
    projectId: 'catho-app-f8a0f',
    storageBucket: 'catho-app-f8a0f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDy0OY713cS2XvdbaX6BjzV83C2t-2ayt4',
    appId: '1:390668051355:ios:fadf753213edbbabd6f73e',
    messagingSenderId: '390668051355',
    projectId: 'catho-app-f8a0f',
    storageBucket: 'catho-app-f8a0f.firebasestorage.app',
    iosBundleId: 'com.cathoapp.cathoApp',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBUyaJM6zeWhRQhTpxUxgHLPVbaCDiNqTA',
    appId: '1:390668051355:web:4d8962c82d94c282d6f73e',
    messagingSenderId: '390668051355',
    projectId: 'catho-app-f8a0f',
    authDomain: 'catho-app-f8a0f.firebaseapp.com',
    storageBucket: 'catho-app-f8a0f.firebasestorage.app',
    measurementId: 'G-99JSQ1PSXF',
  );

}